### ISSUE TITLE
关于插件若干配置问题

### ISSUE THREAD

**Issue by greenhandzdl** [Nambers/Mirai-toolBundle#1]

**Comment by Nambers** [comment]
具体什么意思？
报错or 日志 or 详细描述
MA？

**Comment by greenhandzdl** [comment]
Mirai Android.
报错

**Comment by Nambers** [comment]
> Mirai Android.
> 
> 报错

日志？截图？

**Comment by greenhandzdl** [comment]
诶，刚刚重下了下，发现又可以了
但是还是不可以正常工作，比如撤回
![Screenshot_20220129_125259_io github mzdluo123 mirai android](https://user-images.githubusercontent.com/61241103/151647951-b521bbe5-4212-403c-ae9b-601fcfff5ce6.jpg)
![Screenshot_20220129_125317_io github mzdluo123 mirai android](https://user-images.githubusercontent.com/61241103/151647953-876c4ffa-660a-42b4-aa86-b0144ba21cf1.jpg)
![Screenshot_20220129_125353_io github mzdluo123 mirai android](https://user-images.githubusercontent.com/61241103/151647954-93042a9b-b102-4a90-9748-62c67586e2c7.jpg)
这个是相关日志，然后我权重max设置的1

**Comment by greenhandzdl** [comment]
还有奇怪的是没有生成config
![Screenshot_20220129_125930_io github mzdluo123 mirai android](https://user-images.githubusercontent.com/61241103/151648010-575c8536-e248-4b07-9b58-4ef80c170164.jpg)

**Comment by Nambers** [comment]
那个报错看起来有点像MA里发生的错误，因为插件加载流程在下面而且类包路径是在MA里的
不能撤回有什么日志吗

然后上面截图的路径不是这个插件的id?

**Comment by greenhandzdl** [comment]
id：tech.eritquearcus.RKW
日志？：好像确实是前面插件报错
但是在MA里面，开了调试日志还是看不到撤回相关的

**Comment by Nambers** [comment]
> id：tech.eritquearcus.RKW 日志？：好像确实是前面插件报错 但是在MA里面，开了调试日志还是看不到撤回相关的

撤回阈值是5意味着要在一条信息里包含5次完整的撤回次才撤回，可以看看文档，在你这个配置里，意味着
`NMSLNMSLNMSLNMSLNMSLNMSL`才撤回(6次)
可能没到阈值吧

**Comment by greenhandzdl** [comment]
![Screenshot_20220129_134830_io github mzdluo123 mirai android](https://user-images.githubusercontent.com/61241103/151649308-e4d6152d-95b2-4fff-b53d-77ade85553ff.jpg)
z这样吗？也没撤回

**Comment by Nambers** [comment]
![image](https://user-images.githubusercontent.com/35139537/151649387-d57f529a-0c35-4466-957b-c70d4b7edd6b.png)
欸我这没什么问题

**Comment by greenhandzdl** [comment]
{
	"MaxBorder":1,
	"blockGroupMessage":true,
	"keyWords":[
			["NMSL","WDNMD"]
			],
	"notification":true,
	"readPic":false,
	"readText":true,
	"recallItSelf":true
}

**Comment by greenhandzdl** [comment]
我的文件配置

**Comment by Nambers** [comment]
> 我的文件配置

你`blockGroupMessage`是true

**Comment by greenhandzdl** [comment]
我改成false了，但还是没有拦截

**Comment by greenhandzdl** [comment]
{
	"MaxBorder":1,
	"blockGroupMessage": false,
	"keyWords":[
			["NMSL","WDNMD"]
			],
	"notification":true,
	"readPic":false,
	"readText":true,
	"recallItSelf":true
}
![Screenshot_20220129_135710_com tencent mobileqq](https://user-images.githubusercontent.com/61241103/151649554-4eeef293-591b-4b28-bac4-4af059667b62.jpg)

**Comment by Nambers** [comment]
> { "MaxBorder":1, "blockGroupMessage": false, "keyWords":[ ["NMSL","WDNMD"] ], "notification":true, "readPic":false, "readText":true, "recallItSelf":true } ![Screenshot_20220129_135710_com tencent mobileqq](https://user-images.githubusercontent.com/61241103/151649554-4eeef293-591b-4b28-bac4-4af059667b62.jpg)

阈值是指超过撤回，所以要发两次，或者把阈值改成0才会撤回
此外, 通知也会被撤回，这个在修(

**Comment by greenhandzdl** [comment]
十分感谢，如果Readme 也能这么完善就好了

**Comment by Nambers** [comment]
> 十分感谢，如果Readme 也能这么完善就好了

已经改了些了，因为是很久前写的(<_<)
通知也会被撤回的问题会在下个版本修复

**Comment by greenhandzdl** [comment]
还有大小写能不能模糊下
比如，有的人可能会发nmsl或者nMsl逃避检测

**Comment by Nambers** [comment]
> 还有大小写能不能模糊下 比如，有的人可能会发nmsl或者nMsl逃避检测

1.4.1
https://github.com/Nambers/Mirai-toolBundle/releases/tag/1.4.1

**Comment by greenhandzdl** [comment]
``> > 还有大小写能不能模糊下 比如，有的人可能会发nmsl或者nMsl逃避检测
> 
> 1.4.1 https://github.com/Nambers/Mirai-toolBundle/releases/tag/1.4.1

好像并没有撤回
```bash
{
	"MaxBorder":0,
	"autoUpper":true,
	"blockGroupMessage": false,
	"keyWords":[
			["妈","🐴","全家","傻","逼","鸡巴","礼物","🎁","+我","＋我","赞","贊","微信","兼职","链接","🔗","nmsl","wdnmd","j8","sb"]
			],
	"muteTime":15,
	"notification":true,
	"readPic":true,
	"readText":true,
	"recallItSelf":false
	"type":0
}
```
然后我输入了SB，结果bot并没有撤回并mute（

**Comment by Nambers** [comment]
> 

你这配置文件少了个逗号
然后禁言时间是以秒为单位((
然后我本地测试可以过
然后type = 0, 是仅撤回, 有看文档吗 https://github.com/Nambers/Mirai-toolBundle/tree/main/RKW#:~:text=//%200%20%3D%20%E6%92%A4%E5%9B%9E%2C%201%20%3D%20%E7%A6%81%E8%A8%80%20%2B%20%E6%92%A4%E5%9B%9E%2C%202%20%3D%20%E7%A6%81%E8%A8%80%2C%20%E9%BB%98%E8%AE%A40%2C%20%E5%85%B6%E4%BB%96%E4%B8%8D%E6%93%8D%E4%BD%9C 😕

**Comment by greenhandzdl** [comment]
> > 
> 
> 你这配置文件少了个逗号 然后禁言时间是以秒为单位(( 然后我本地测试可以过 然后type = 0, 是仅撤回, 有看文档吗 https://github.com/Nambers/Mirai-toolBundle/tree/main/RKW#:~:text=//%200%20%3D%20%E6%92%A4%E5%9B%9E%2C%201%20%3D%20%E7%A6%81%E8%A8%80%20%2B%20%E6%92%A4%E5%9B%9E%2C%202%20%3D%20%E7%A6%81%E8%A8%80%2C%20%E9%BB%98%E8%AE%A40%2C%20%E5%85%B6%E4%BB%96%E4%B8%8D%E6%93%8D%E4%BD%9C 😕

你确定你更新了文档吗

**Comment by Nambers** [comment]
> > > 
> > 
> > 
> > 你这配置文件少了个逗号 然后禁言时间是以秒为单位(( 然后我本地测试可以过 然后type = 0, 是仅撤回, 有看文档吗 https://github.com/Nambers/Mirai-toolBundle/tree/main/RKW#:~:text=//%200%20%3D%20%E6%92%A4%E5%9B%9E%2C%201%20%3D%20%E7%A6%81%E8%A8%80%20%2B%20%E6%92%A4%E5%9B%9E%2C%202%20%3D%20%E7%A6%81%E8%A8%80%2C%20%E9%BB%98%E8%AE%A40%2C%20%E5%85%B6%E4%BB%96%E4%B8%8D%E6%93%8D%E4%BD%9C 😕
> 
> 你确定你更新了文档吗

?没听懂什么意思，但是这个文档是3天前就加的
https://github.com/Nambers/Mirai-toolBundle/commit/36b306f17450b65a5f3c0a980b4354237a562f75#diff-04042a3250ee7d4939b6d9faf1a6ff1803c59898c7316d1518ea1727cec93e70R37

**Comment by greenhandzdl** [comment]
> > > > 
> > > 
> > > 
> > > 你这配置文件少了个逗号 然后禁言时间是以秒为单位(( 然后我本地测试可以过 然后type = 0, 是仅撤回, 有看文档吗 https://github.com/Nambers/Mirai-toolBundle/tree/main/RKW#:~:text=//%200%20%3D%20%E6%92%A4%E5%9B%9E%2C%201%20%3D%20%E7%A6%81%E8%A8%80%20%2B%20%E6%92%A4%E5%9B%9E%2C%202%20%3D%20%E7%A6%81%E8%A8%80%2C%20%E9%BB%98%E8%AE%A40%2C%20%E5%85%B6%E4%BB%96%E4%B8%8D%E6%93%8D%E4%BD%9C 😕
> > 
> > 
> > 你确定你更新了文档吗
> 
> ?没听懂什么意思，但是这个文档是3天前就加的 [36b306f#diff-04042a3250ee7d4939b6d9faf1a6ff1803c59898c7316d1518ea1727cec93e70R37](https://github.com/Nambers/Mirai-toolBundle/commit/36b306f17450b65a5f3c0a980b4354237a562f75#diff-04042a3250ee7d4939b6d9faf1a6ff1803c59898c7316d1518ea1727cec93e70R37)

![Screenshot_20220131_130654_com huawei browser](https://user-images.githubusercontent.com/61241103/151741850-8a0963d0-5e33-417c-a579-78c96d411e91.jpg)
我说的配置文件

**Comment by Nambers** [comment]
那些nullable(带问号的)都是可选的
不更新“示例”配置文件也没问题吧
当然我回去后也顺带更新下吧，不过配置项的说明全在上面



Eritque&nbsp;arcus



------------------ Original ------------------
From: greenhandzdl ***@***.***&gt;
Date: Mon, Jan 31, 2022 1:08 PM
To: Nambers/Mirai-toolBundle ***@***.***&gt;
Cc: Eritque arcus ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [Nambers/Mirai-toolBundle] 关于插件若干配置问题 (Issue #1)






你这配置文件少了个逗号 然后禁言时间是以秒为单位(( 然后我本地测试可以过 然后type = 0, 是仅撤回, 有看文档吗 https://github.com/Nambers/Mirai-toolBundle/tree/main/RKW#:~:text=//%200%20%3D%20%E6%92%A4%E5%9B%9E%2C%201%20%3D%20%E7%A6%81%E8%A8%80%20%2B%20%E6%92%A4%E5%9B%9E%2C%202%20%3D%20%E7%A6%81%E8%A8%80%2C%20%E9%BB%98%E8%AE%A40%2C%20%E5%85%B6%E4%BB%96%E4%B8%8D%E6%93%8D%E4%BD%9C 😕

你确定你更新了文档吗

?没听懂什么意思，但是这个文档是3天前就加的 36b306f#diff-04042a3250ee7d4939b6d9faf1a6ff1803c59898c7316d1518ea1727cec93e70R37


我说的配置文件
